---
new_page_extension: md
auto_deploy: false
admin_path: src/portal
webhook_url: 
sections:
- type: heading
  label: Intro
- type: heading
  label: Why Coaching
- type: heading
  label: Philosophy
- type: heading
  label: Testimonials
- type: heading
  label: Certifications
- type: heading
  label: How it works
upload_dir: src/static/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
